substitutions: # default values
  _NODE: '8.11.0'
  _BUCKET: 'bootstrap-cache' # you could make your gcs public or require contributors have their own
  # _USERNAME: 'christophersanson'
  # _ACCESS_KEY: '2f2a2bf3-6b6c-49a7-a659-7c727c90afbc'

steps:
# images will be cached on the worker for production and this step will be removed
- id: 'Pull images'
  name: gcr.io/cloud-builders/docker
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        docker pull gcr.io/cloud-builders/npm:node-${_NODE}
        docker pull digitallyseamless/nodejs-bower-grunt
        docker pull ruby
        docker pull jekyll/jekyll

# Fetch cache
- id: 'Fetch cache'
  name: gcr.io/cloud-builders/gsutil
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        gsutil cp gs://${_BUCKET}/node_modules-${_NODE}.tar.gz previous_node_modules.tar.gz
        tar -xzf previous_node_modules.tar.gz node_modules
        gsutil cp gs://${_BUCKET}/bundle.tar.gz previous_bundle.tar.gz
        tar -xzf previous_bundle.tar.gz vendor/bundle

# Install bundle
- id: 'Install vendor/bundle'
  name: ruby
  args: ['bundle', 'install', '--deployment']

# Install node_modules
- id: 'Install node_modules'
  name: gcr.io/cloud-builders/npm:node-${_NODE}
  args: ['install']

# Run SauceLabs Tests
- id: 'Run Grunt SauceLabs Tests'
  name: digitallyseamless/nodejs-bower-grunt
  args: 
    - grunt
    - --username=$_USERNAME
    - --access-key=$_ACCESS_KEY
    - --build-id=$BUILD_ID

- id: 'docs-compile'
  name: jekyll/jekyll
  dir: './dist'
  args: ['bundle', 'exec', 'jekyll', 'build']

- id: 'docs-lint'
  name: gcr.io/cloud-builders/npm:node-${_NODE}
  dir: './dist'
  args: ['run', 'docs-lint']

- id: 'bundlesize'
  name: gcr.io/cloud-builders/npm:node-${_NODE}
  dir: './dist'
  args: ['run', 'bundlesize']

# Cache dependencies
- id: 'Push cache'
  name: gcr.io/cloud-builders/gsutil
  entrypoint: 'sh'
  args:
      - '-c'
      - |
        tar -czf node_modules.tar.gz node_modules
        gsutil cp node_modules.tar.gz gs://${_BUCKET}/node_modules-${_NODE}.tar.gz
        tar -czf bundle.tar.gz vendor/bundle
        gsutil cp bundle.tar.gz gs://${_BUCKET}/bundle.tar.gz
