substitutions:
  _NODE: '8.11.0' # default value

steps:
- id: 'Install vendor/bundle'
  name: ruby
  args: ['bundle', 'install', '--deployment']

- id: 'Install node_modules'
  name: gcr.io/cloud-builders/npm:node-${_NODE}
  args: ['install']

# rebuild any preinstalled modules from mac to work on linux
- id: 'Rebuild node_modules'
  name: gcr.io/cloud-builders/npm:node-${_NODE}
  args: ['rebuild', 'iltorb', 'node-sass']

# Run Tests
- id: 'js-test'
  name: gcr.io/$PROJECT_ID/chromium-xvfb-js:${_NODE}
  args: ['npm', 'test']

- id: 'docs-compile'
  name: jekyll/jekyll
  dir: './dist'
  args: ['bundle', 'exec', 'jekyll', 'build']

- id: 'docs-lint'
  name: gcr.io/cloud-builders/npm:node-${_NODE}
  dir: './dist'
  args: ['run', 'docs-lint']

- id: 'bundlesize'
  name: gcr.io/cloud-builders/npm:node-${_NODE}
  dir: './dist'
  args: ['run', 'bundlesize']